#Even Fibonacci numbers
#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibo(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a

sum = 0
for i in range(1,10000):
	if fibo(i) > 4000000:
		break
	if fibo(i)%2.0 == 0:
		sum = sum + fibo(i)
print sum

#4613732
#Congratulations, the answer you gave to problem 2 is correct.